Anz.LMJ/Anz.LMJ.StartUp/Controllers/LayoutController.cs
using Anz.LMJ.BLO.LogicObjects.CommonObjects;
using Anz.LMJ.BLO.ContentObjects;
using Anz.LMJ.BLO.LogicObjects.Submission;
using Anz.LMJ.WebServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Text;

namespace Anz.LMJ.StartUp.Controllers
{
    public class LayoutController : Controller
    {
        // GET: Layout
        #region Services
        ContentServices _ContentServices = new ContentServices();
        HomeServices _HomeServices = new HomeServices();
        #endregion

        #region Footer
        public ActionResult Footer()
        {
          try{
                List<long> ids = new List<long>();
                DynamicResponse<SelectLO> options = new DynamicResponse<SelectLO>();
                DynamicResponse<List<Options>> articlestype = new DynamicResponse<List<Options>>();
                DynamicResponse<List<SubmissionLO>> response = new DynamicResponse<List<SubmissionLO>>();

                options = _HomeServices.GetOption();
                ViewBag.options = options.Data;
                Footer footer = _ContentServices.GetContent<Footer>(ContentServices.ServiceTables.Footer, 1).Contents.FirstOrDefault();
                ViewBag.footer = footer;
                string[] arr = footer.CategoryIds.Split(',');
                foreach (string id in (arr))
                {
                    ids.Add(long.Parse(id));
                }
                articlestype = _HomeServices.GetArticlesType(ids);
                if (articlestype.HttpStatusCode != HttpStatusCode.OK)
                {
                    return RedirectToAction("Index", "Oops");
                }
                ViewBag.articlestype = articlestype.Data;
                arr = footer.RecentArticleIds.Split(',');
                foreach (string id in (arr))
                {
                    ids.Add(long.Parse(id));
                }
                response = _HomeServices.GetArticles(ids);
                if (response.HttpStatusCode != HttpStatusCode.OK)
                {
                    return RedirectToAction("Index", "Oops");
                }
                ViewBag.Issues = response.Data;
                arr = footer.ContactIds.Split(',');
                ViewBag.contact = arr;
                var html = new StringBuilder("");

                Contact contact = _ContentServices.GetContent<Contact>(ContentServices.ServiceTables.Contact, 1).Contents.FirstOrDefault();
                for (int i = 0; i < arr.Length; i++)
                {
                    html.Append("<strong>" + arr[i].Trim() + "</strong>: " + Helper.GetPropValue<string>(contact, arr[i].Trim()) + "<br/>");
                }
                ViewBag.contactdata = html;
                ViewBag.contact = contact;
                List<FooterMenu> footerlinks = _ContentServices.GetContent<FooterMenu>(ContentServices.ServiceTables.FooterMenu, 9999).Contents.ToList();
                ViewBag.footerlinks = footerlinks;

                return PartialView("_PartialViewFooter", new ViewDataDictionary { new KeyValuePair<string, object>("footer", ViewBag.footer), new KeyValuePair<string, object>("footerlinks", ViewBag.footerlinks), new KeyValuePair<string, object>("contactdata", ViewBag.contactdata), new KeyValuePair<string, object>("contact", ViewBag.contact), new KeyValuePair<string, object>("options", ViewBag.options), new KeyValuePair<string, object>("articlestype", ViewBag.articlestype), new KeyValuePair<string, object>("Issues", ViewBag.Issues) });

            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Oops");
            }

        }

        #endregion

        #region Header
        public ActionResult Header()
        {
            try
            {
                Contact contact = _ContentServices.GetContent<Contact>(ContentServices.ServiceTables.Contact, 1).Contents.FirstOrDefault();
                ViewBag.contact = contact;
                return PartialView("_PartialViewHeader", new ViewDataDictionary { new KeyValuePair<string, object>("contact", ViewBag.contact) });

            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Oops");
            }

       }
        #endregion

        #region Search Article 

        [HttpPost]
        public ActionResult SearchArticle(long submissionid, long issueid, long volumeid, long articletype, long author, long sectionid, string issuetitle)
        {

            try
            {

                DynamicResponse<List<SubmissionLO>> submission = _HomeServices.SearchArticle(submissionid, issueid, volumeid, articletype, author, sectionid, issuetitle);
                ViewBag.articles = submission.Data;
                if (submission.HttpStatusCode != HttpStatusCode.OK)
                {
                    return RedirectToAction("Index", "Oops");
                }

                return PartialView("~/Views/Home/_PartialViewArticles.cshtml", submission.Data);
            }


            catch (Exception ex)
            {
                return RedirectToAction("Index", "Oops");
            }
        }
        #endregion

    }
}

Anz.LMJ/Anz.LMJ.StartUp/Views/Shared/_AdminLayout.cshtml
@using System.Xml;

<!DOCTYPE html>
<html lang="en-us">
<head>

    <title>LMJ | @ViewBag.Title</title>

    <meta charset="utf-8">
    <meta name="description" Scripts="">
    <meta name="author" Scripts="">
    <meta name="viewport" Scripts="width=device-width" />
    <meta name="apple-mobile-web-app-capable" Scripts="yes">
    <meta name="apple-mobile-web-app-status-bar-style" Scripts="black">
    <meta name="viewport" Scripts="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">

    <!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    @Styles.Render("~/Content/cms/bootstrap.min.css")
    @Styles.Render("~/Content/cms/font-awesome.min.css")
    @Styles.Render("~/Content/cms/smartadmin-production-plugins.min.css")
    @Styles.Render("~/Content/cms/smartadmin-production.min.css")
    @Styles.Render("~/Content/cms/smartadmin-skins.min.css")
    @Styles.Render("~/Content/cms/smartadmin-rtl.min.css")
    @*@Styles.Render("~/Content/editor.css")*@


    <link href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
    <link href="~/Scripts/cms/rowReorder.dataTables.min.css" rel="stylesheet">

    <style>
        .close {
            float: right;
            font-size: 24.5px;
        }

        .modal-title {
            font-size: 21px;
            margin: 0;
            line-height: 1.42857143;
            color: #474544;
            font-weight: 500;
        }

        .modal-header {
            background: #e5e5e5;
        }

        .btn-default {
            margin-top: -10px;
        }

        #add_DiscussionPreReview_files {
            margin-top: 0px !important;
        }

        .btn-secondary {
            margin-top: -10px !important;
            background-color: #ece9e9;
        }

        #logo {
            color: #000;
            font-size: 2.5rem;
            text-align: left;
        }

        .jarviswidget-color-darken > header {
            background: linear-gradient(to left, #AD0202, #AD0202) !important;
        }

        .btn-primary.active, .btn-primary:active, .btn-primary:hover, .open > .dropdown-toggle.btn-primary {
            color: #fff;
            background-color: #AD0202;
            border-color: #AD0202;
        }

        .btn-primary {
            color: #fff;
            background-color: #AD0202;
            border-color: #AD0202;
        }

        .jarviswidget-ctrls a {
            text-decoration: none;
            font-size: 15px !important;
            text-align: center;
            display: inline-block;
            line-height: 0px !important;
            padding: 0;
            margin: 0;
            color: #333;
        }

        #btn-datatable {
            color: #AD0202 !important;
        }

        .btn-datatable {
            border: 1px solid #AD0202 !important;
            color: #AD0202 !important;
            background-color: #fff !important;
            padding: 5px 12px;
        }
    </style>


</head>
<body>
    <div class="se-pre-con"></div>
    <header id="header">
        <div id="logo-group">

            <!-- PLACE YOUR LOGO HERE -->
            <span id="logo"> LMJ </span>
            <!-- END LOGO PLACEHOLDER -->
            <!-- Note: The activity badge color changes when clicked and resets the number to 0
            Suggestion: You may want to set a flag when this happens to tick off all checked messages / notifications -->
            <span id="activity" class="activity-dropdown"> <i class="fa fa-user"></i> <b class="badge"> 21 </b> </span>

            <!-- AJAX-DROPDOWN : control this dropdown height, look and feel from the LESS variable file -->
            <div class="ajax-dropdown">

                <!-- the ID links are fetched via AJAX to the ajax container "ajax-notifications" -->
                <div class="btn-group btn-group-justified" data-toggle="buttons">
                    @*<label class="btn btn-default">
                            <input type="radio" name="activity" id="/Home">
                            Msgs (14)
                        </label>
                        <label class="btn btn-default">
                            <input type="radio" name="activity" id="/home">
                            notify (3)
                        </label>
                        <label class="btn btn-default">
                            <input type="radio" name="activity" id="/home">
                            Tasks (4)
                        </label>*@
                </div>

                <!-- notification content -->
                <div class="ajax-notifications custom-scroll">

                    <div class="alert alert-transparent">
                        <h4>Click a button to show messages here</h4>
                    </div>

                    <div class="alert alert-transparent">
                        <h4>Click a button to show messages here</h4>
                    </div>

                    @*<i class="fa fa-lock fa-4x fa-border"></i>*@

                </div>
                <!-- end notification content -->
                <!-- footer: refresh area -->
                @*<span>
                        Last updated on: 12/12/2013 9:43AM
                        <button type="button" data-loading-text="<i class='fa fa-refresh fa-spin'></i> Loading..." class="btn btn-xs btn-default pull-right">
                            <i class="fa fa-refresh"></i>
                        </button>
                    </span>*@
                <!-- end footer -->

            </div>
            <!-- END AJAX-DROPDOWN -->
        </div>

        <!-- #PROJECTS: projects dropdown -->
        <div class="project-context hidden-xs">

            @*<span class="label">Projects:</span>
                <span class="project-selector dropdown-toggle" data-toggle="dropdown">Recent projects <i class="fa fa-angle-down"></i></span>*@

            <!-- Suggestion: populate this list with fetch and push technique -->
            @*<ul class="dropdown-menu">
                    <li>
                        <a href="javascript:void(0);">Online e-merchant management system - attaching integration with the iOS</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);">Notes on pipeline upgradee</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);">Assesment Report for merchant account</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="javascript:void(0);"><i class="fa fa-power-off"></i> Clear</a>
                    </li>
                </ul>*@
            <!-- end dropdown-menu-->

        </div>
        <!-- end projects dropdown -->
        <div class="pull-right rightpp">
            <div id="hide-menu" class="btn-header pull-right">
                <span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu"><i class="fa fa-reorder"></i></a> </span>
            </div>

            <div id="logout" data-target="#ModelLogout" data-toggle="modal" class="btn-header transparent pull-right">
                <span> <a><i class="fa fa-sign-out"></i></a> </span>
            </div>

        </div>

    </header>


    <aside id="left-panel">

        <nav>

            <ul>
                @{

                    XmlDocument doc = new XmlDocument();
                    string XMLPath = HttpContext.Current.Server.MapPath("~/AdminMenu.xml");
                    doc.Load(XMLPath);
                    XmlNode MainNode = doc.ChildNodes[1];
                    foreach (XmlNode child in MainNode.ChildNodes)
                    {

                        <li class="main-menu @child.Attributes["class"].Value">

                            <a href="@child.Attributes["link"].Value" title="@child.Attributes["name"].Value">
                                <i class="@child.Attributes["icon"].Value"></i>
                                <span class="menu-item-parent">
                                    @child.Attributes["name"].Value
                                </span>
                            </a>

                            @if (@child.HasChildNodes)
                            {
                                <ul>

                                    @foreach (XmlNode subnode in child.ChildNodes)
                                    {
                                        <li class="sub-menu @subnode.Attributes["class"].Value">
                                            <a href="@subnode.Attributes["link"].Value" title=""><span class="menu-item-parent">@subnode.Attributes["name"].Value</span></a>
                                        </li>
                                    }

                                </ul>
                            }

                        </li>

                    }
                }
            </ul>
        </nav>

    </aside>


    <div>
        @RenderBody()
    </div>

    <div class="page-footer">
        <div class="row">
            <div class="col-xs-12 col-sm-6">
                <span class="txt-color-white">LMJ <span class="hidden-xs"> </span> © 2020  All rights reserved.</span>
            </div>
        </div>
    </div>




    <div class="modal fade ModelLogout" id="ModelLogout" tabindex="-1" role="dialog" aria-labelledby="ModelLogout" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="UploadSubmissionFiles">Logout</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body ">
                    <div class="row" style="padding-left: 2%;">
                        Are You Sure You Want to Logout
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary confim-logout">Yes</button>
                </div>
            </div>
        </div>
    </div>


</body>


</html>



<!--================================================== -->
<!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
<script data-pace-options='{ "restartOnRequestAfter": true }' src="~/Scripts/cms/plugin/pace/pace.min.js"></script>

@*<script>
        if (!window.jQuery) {
            document.write('<script src="~/Scripts/cms/libs/jquery-2.1.1.min.js"></script>');
        }
    </script>


    <script>
        if (!window.jQuery.ui) {
            document.write('<script src="~/Scripts/cms/libs/jquery-ui-1.10.3.min.js"></script>');
        }
    </script>*@

<script src="~/Scripts/cms/libs/jquery-2.1.1.min.js"></script>
<script src="~/Scripts/cms/app.config.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/cms/Admin/jquery.dataTables.min.js"></script>
<script src="~/Scripts/cms/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script>
<script src="~/Scripts/cms/notification/SmartNotification.min.js"></script>
<script src="~/Scripts/cms/smartwidgets/jarvis.widget.min.js"></script>
<script src="~/Scripts/cms/plugin/easy-pie-chart/jquery.easy-pie-chart.min.js"></script>
<script src="~/Scripts/cms/plugin/sparkline/jquery.sparkline.min.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/cms/plugin/masked-input/jquery.maskedinput.min.js"></script>
<script src="~/Scripts/cms/plugin/select2/select2.min.js"></script>
<script src="~/Scripts/cms/plugin/bootstrap-slider/bootstrap-slider.min.js"></script>
<script src="~/Scripts/cms/plugin/msie-fix/jquery.mb.browser.min.js"></script>
<script src="~/Scripts/cms/plugin/fastclick/fastclick.min.js"></script>
<script src="~/Scripts/cms/plugin/datatables/dataTables.buttons.min.js"></script>
<script src="~/Scripts/cms/plugin/datatables/jszip.min.js"></script>
<script src="~/Scripts/cms/plugin/datatables/buttons.html5.min.js"></script>
<script src="~/Scripts/cms/plugin/bootstrap-wizard/jquery.bootstrap.wizard.min.js"></script>
<script src="~/Scripts/cms/plugin/superbox/superbox.min.js"></script>
<script src="~/Scripts/cms/plugin/ckeditor/ckeditor.js"></script>
<script src="~/Scripts/cms/app.min.js"></script>
<script src="~/Scripts/cms/libs/jspdf.min.js"></script>
<script src="~/Scripts/cms/editor.js"></script>
<script src="~/Scripts/cms/CmsJquery.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.js"></script>

@*<script src="~/Scripts/cms/libs/jquery-3.5.1.js"></script>*@
<script src="~/Scripts/cms/libs/jquery.dataTables.min.js"></script>
<script src="~/Scripts/cms/libs/dataTables.rowReorder.min.js"></script>


<script type="text/javascript">

    $(document).ready(function () {

        pageSetUp();

        $("#logout").on("click", function (event) {
            event.preventDefault();
            console.log("click");
            $('#Logout_Modal').modal('show');
        });





        $(".confim-logout").on("click", function (event) {
            event.preventDefault();
            location.href = "/Home/Logout/";
        });
    })

</script>

Anz.LMJ/Anz.LMJ.StartUp/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>JML/LMJ | @ViewBag.Title</title>
    <meta name="description" content="JOURNAL MEDICAL LIBANAIS / LEBANESE MEDICAL JOURNAL">
    <meta name="keywords" content="JOURNAL, MEDICAL, LIBANAIS,JML,LMJ,LEBANESE, MEDICAL, JOURNAL">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <link href="~/Content/img/fav.jpg" rel="icon">
    <link href="~/Content/img/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,500,600,700,700i|Montserrat:300,400,500,600,700" rel="stylesheet">

    <link href="~/Content/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/Content/lib/ionicons/css/ionicons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/Content/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Content/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/Content/lib/lightbox/css/lightbox.min.css" >
    <link rel="stylesheet" href="~/Content/css/stylecss.css">
    <style>
        .fa {
            padding-right: 0.25rem;
        }

        .footer-img {
            width: 100%;
            border: 1px solid #f3f4f7;
            background: #f3f4f7;
            cursor: pointer;
        }

        .mg-btm {
            margin-bottom: 1rem;
        }

        .footer-second {
            background: #f1f2f5;
            padding: 60px 0 30px 0;
        }

        span {
            font-family: OpenSansRegular;
            color: #161616;
        }

        #footer h6 {
            font-size: 14px;
            margin: 0;
        }
    </style>
</head>



<body>

    <header id="header">
        <div class="logo float-left desktop-none">
            <a href="/Home" class="scrollto"><img src="~/Content/img/LMJ-logo.jpg" alt="LMJ-LOGO" class="img-fluid img-logo"></a>
        </div>

        @Html.Action("Header", "Layout")
        <div class="topbar">
            <div class="container border-2">
                <div class="row" style="width: 100%">
                    <div class="col-md-6">
                        <a href="/Home" class="scrollto"><img src="~/Content/img/LMJ-logo.jpg" alt="LMJ-LOGO" class="img-fluid img-logo"></a>
                    </div>
                    <div class="col-md-4">
                        <div class="search">
                            <input type="text" class="searchTerm" value="" placeholder="Search">
                            <button type="submit" class="searchButton">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <button data-toggle="modal" data-target="#myModalAdvancedSearch" class="btn btn-primary AdvancedSearch">Advanced search</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container topbar border-3">
            <nav class="main-nav d-none d-lg-block">
                <ul>
                    <li id="Home" class="active"><a href="/Home/index">Home</a></li>

                    <li id="Articles"><a href="/Home/Articles">Articles</a></li>
                    @*<li id="SubmitArticles"><a href="/Home/SubmitArticles">Submit your article</a></li>*@
                    <li id="EditorialBoard"><a href="/Home/EditorialBoards">Editorial board</a></li>
                    <li id="AboutUs"><a href="/Home/About">About Us</a></li>
                    <li id="ContactUs"><a href="/Home/Contact">Contact us</a></li>
                </ul>
            </nav><!-- .main-nav -->

        </div>
        <div class="container stp-bar">
            <div class="logo float-left">
                <a href="/Home" class="scrollto"><img src="~/Content/img/LMJ-logo.jpg" alt="LMJ-LOGO" class="img-fluid img-logo"></a>
            </div>
            <nav class="main-nav float-right d-none d-lg-block">
                <ul>
                    <li id="Home" class="active"><a href="/Home/index">Home</a></li>
                    <li id="AboutUs"><a href="/Home/About">About Us</a></li>
                    <li id="Articles"><a href="/Home/Articles">Articles</a></li>
                    <li id="SubmitArticles"><a href="/Home/SubmitArticles">Submit your article</a></li>
                    <li id="EditorialBoard"><a href="#">Editorial board</a></li>
                    <li id="ContactUs"><a href="/ContactUs">Contact us</a></li>
                </ul>
            </nav>
        </div>
    </header>

    @RenderBody()



    @Html.Action("Footer", "Layout")


    <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
    <div id="preloader"></div>

    <script src="~/Content/lib/jquery/jquery.min.js"></script>
    <script src="~/Content/lib/jquery/jquery-migrate.min.js"></script>
    <script src="~/Content/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Content/lib/easing/easing.min.js"></script>
    <script src="~/Content/lib/mobile-nav/mobile-nav.js"></script>
    <script src="~/Content/lib/wow/wow.min.js"></script>
    <script src="~/Content/lib/waypoints/waypoints.min.js"></script>
    <script src="~/Content/lib/counterup/counterup.min.js"></script>
    <script src="~/Content/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/Content/lib/isotope/isotope.pkgd.min.js"></script>
    <script src="~/Content/lib/lightbox/js/lightbox.min.js"></script>
    <script src="~/Content/contactform/contactform.js"></script>
    <script src="~/Content/js/mainjs.js"></script>

    <script>
        var carousel = function () {
            $('.carousel-testimony').owlCarousel({
                center: true,
                loop: true,
                items: 1,
                margin: 30,
                stagePadding: 0,
                nav: false,
                navText: ['<span class="ion-ios-arrow-back">', '<span class="ion-ios-arrow-forward">'],
                responsive: {
                    0: {
                        items: 1
                    },
                    600: {
                        items: 2
                    },
                    1000: {
                        items: 3
                    }
                }
            });

        };
        carousel();

        if ($(window).width() > 992) {
            $(window).scroll(function () {
                if ($(this).scrollTop() > 40) {
                    $('#header').addClass("fixed-top");
                    // add padding top to show content behind navbar
                    $('body').css('padding-top', $('.navbar').outerHeight() + 'px');
                } else {
                    $('#header').removeClass("fixed-top");
                    // remove padding top from body
                    $('body').css('padding-top', '0');
                }
            });
        }
    </script>

</body>

</html>

Anz.LMJ/Anz.LMJ.StartUp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>