Anz.LMJ/Anz.LMJ.StartUp/Controllers/ManagementController.cs
using Anz.LMJ.BLO.LogicObjects.CommonObjects;
using Anz.LMJ.BLO.LogicObjects.User;
using Anz.LMJ.WebServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using Anz.LMJ.BLL.Logic;
using Anz.LMJ.BLO.LogicObjects.Submission;
using Anz.LMJ.FrontEnd;
using System.IO;

namespace Anz.LMJ.StartUp.Controllers
{
    public class ManagementController : Controller
    {
        public void setSession()
        {

            Session["userId"] = "1";
        }

        // GET: Dashboard
        public ActionResult Index()
        {
           
            #region Services
            ManagementService _ManagementService = new ManagementService();
            #endregion
            try
            {
             
                if (Session["userId"] == null)
                    return RedirectToAction("Index", "Admin");
                long userId = long.Parse(Session["userId"].ToString());
                DynamicResponse<UserQueueLO> queue = _ManagementService.GetQueue(userId, 1);
                DynamicResponse<List<SubmissionLO>> unassigned = _ManagementService.GetUnAssigned(userId);
                

                if (queue.HttpStatusCode != HttpStatusCode.OK)
                {
                    return RedirectToAction("Index", "Oops");
                }

                ViewBag.unassigned = unassigned.Data;
                ViewBag.queue = queue.Data;
                return View();
            }
            catch (Exception ex)
            {
                return RedirectToAction("");
            }

        }



        [CheckUserSession]
        public ActionResult MainMenu()
        {
            try
            {
                return View("MainMenu");
            }
            catch (Exception ex)
            {

                throw;
            }
        }




        public JsonResult NewsLetter()
        {
            #region Logics
            SubmissionLogic _SubmissionLogic = new SubmissionLogic();
            #endregion

            try
            {

                DynamicResponse<List<NewsletterLO>> response = new DynamicResponse<List<NewsletterLO>>();
                response = _SubmissionLogic.GetNewsLetter();
                return Json(response, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                throw;
            }

        }

        #region management


        [CheckUserSession]
        public ActionResult GetNewsletter(long id)
        {
            try
            {

                #region Logics
                SubmissionLogic _SubmissionLogic = new SubmissionLogic();
                #endregion

                if (Session["userId"] == null)
                    return RedirectToAction("Index", "Admin");
                DynamicResponse<NewsletterLO> response = new DynamicResponse<NewsletterLO>();
                response = _SubmissionLogic.GetNewsLetter(id);
                if (response.HttpStatusCode != HttpStatusCode.OK)
                {
                    return RedirectToAction("Index", "Oops");
                }

                return View(response.Data);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Oops");
            }

        }

        [CheckUserSession]
        public ActionResult Newsletters()
        {


            #region Logics
            SubmissionLogic _SubmissionLogic = new SubmissionLogic();
            #endregion

            if (Session["userId"] == null)
                return RedirectToAction("Index", "Admin");
            try
            {
                DynamicResponse<List<NewsletterLO>> response = new DynamicResponse<List<NewsletterLO>>();
                response = _SubmissionLogic.GetNewsLetter();
                if (response.HttpStatusCode != HttpStatusCode.OK)
                {
                    return RedirectToAction("Index", "Oops");
                }

                return View(response.Data);
            }
            catch (Exception ex)
            {

                throw;
            }
        }


        [CheckUserSession]
        public ActionResult AddNewsletterForm()
        {
            try
            {
                return View("NewsletterForm");
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        [CheckUserSession]
        public ActionResult AddNewsletter(NewsletterLO toAdd)
        {
            #region Logics
            SubmissionLogic _SubmissionLogic = new SubmissionLogic();
            #endregion
            DynamicResponse<NewsletterLO> response = new DynamicResponse<NewsletterLO>();

            if (Session["userId"] == null)
                return Json("session-null");

            long userId = long.Parse(Session["userId"].ToString());
            try
            {
                string path_images = Server.MapPath("~/NewsletterImages/");
                if (!Directory.Exists(path_images))
                {
                    Directory.CreateDirectory(path_images);
                }

                if (toAdd.PostedFileImage != null)
                {
                    string extension = Path.GetExtension(toAdd.PostedFileImage.FileName);
                    string Name = Path.GetFileNameWithoutExtension(toAdd.PostedFileImage.FileName);
                    string newName = Name + DateTime.Now.ToString("yyyyMMddHHmmss") + extension;
                    toAdd.PostedFileImage.SaveAs(path_images + newName);
                    toAdd.Image = newName;
                }

                response = _SubmissionLogic.AddNewsletter(toAdd, userId);
                if (response.HttpStatusCode != HttpStatusCode.OK)
                {
                    return RedirectToAction("Index", "Oops");
                }
                return RedirectToAction("Newsletters");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Oops");
            }

        }

        public ActionResult EditNewsletter(NewsletterLO toEdit)
        {
            #region Logics
            SubmissionLogic _SubmissionLogic = new SubmissionLogic();
            #endregion
            DynamicResponse<long> response = new DynamicResponse<long>();

            if (Session["userId"] == null)
                return RedirectToAction("Index", "Admin");

            long userId = long.Parse(Session["userId"].ToString());

            try
            {
                string path_images = Server.MapPath("~/NewsletterImages/");
                if (!Directory.Exists(path_images))
                {
                    Directory.CreateDirectory(path_images);
                }

                if (toEdit.PostedFileImage != null)
                {
                    string extension = Path.GetExtension(toEdit.PostedFileImage.FileName);
                    string Name = Path.GetFileNameWithoutExtension(toEdit.PostedFileImage.FileName);
                    string newName = Name + DateTime.Now.ToString("yyyyMMddHHmmss") + extension;
                    toEdit.PostedFileImage.SaveAs(path_images + newName);
                    toEdit.Image = newName;
                }
                toEdit.UserId = userId;
                response = _SubmissionLogic.EditNewsletter(toEdit);
                if (response.HttpStatusCode != HttpStatusCode.OK)
                {
                    return RedirectToAction("Index", "Oops");
                }
                return RedirectToAction("Newsletters");
            }
            catch (Exception ex)
            {

                return RedirectToAction("Index", "Oops");
            }

        }
        #endregion
        #region Return Json
        [ActionName("unassign")]
        [HttpGet]
        /// <summary>
        /// list of unassiged submission that needs editors.
        /// only returns submission when the user is editor or author
        /// </summary>
        /// <param name="id">user id</param>
        /// <returns></returns>
        public JsonResult UnAssignedSubmissionsNeedEditors(long id)
        {
            try
            {

            }
            catch (Exception ex)
            {

                throw;
            }

            return Json("", JsonRequestBehavior.AllowGet);

        }


        [ActionName("unreview")]
        [HttpGet]
        /// <summary>
        /// list of unreviewed submission that needs reviewers
        /// only returns submission when the user is reviewer or author
        /// </summary>
        /// <param name="id">user id</param>
        /// <returns></returns>
        public JsonResult UnReviewedSubmissionsNeedReviewers(long id)
        {
            try
            {

            }
            catch (Exception ex)
            {

                throw;
            }
            return Json("", JsonRequestBehavior.AllowGet);

        }




        #endregion

    }
}

Anz.LMJ/Anz.LMJ.StartUp/Views/Management/GetNewsletter.cshtml
@using Anz.LMJ.BLO.LogicObjects.Submission
@model NewsletterLO
@{
    ViewBag.Title = "GetNewsletter";
    Layout = "~/Views/Shared/_ManagementLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>

    <style>
        #newsletter-form {
            width: 80%;
        }
        #content {
            text-align: right;
        }
    </style>

    <meta name="viewport" content="width=device-width" />
    <title>Newsletter</title>
</head>
<body>

    <div id="main" role="main">
        <div id="content">
            <div class="row">
                @using (Html.BeginForm("EditNewsletter", "Management", FormMethod.Post, new { @class = "EditNewsletter", enctype = "multipart/form-data" }))
                {<div class="row">
                        <div class="col-xs-3 col-sm-2 col-lg-1">
                            <label class="col-sm-12 control-label">
                                <strong>Name</strong>
                            </label>
                        </div>
                        <div class="col-xs-9 col-sm-4 col-md-4 col-lg-4">
                            <div class="form-group">
                                <input class="form-control input-md" placeholder="Name" name="Name" type="text" value="@Model.Name">
                                <input class="form-control input-md" name="Id" type="hidden" value="@Model.Id">
                            </div>
                        </div>
                        <div class="col-xs-3 col-sm-2  col-lg-2">
                            <label class="col-sm-12 control-label">
                                <strong>Date</strong>
                            </label>
                        </div>
                        <div class="col-xs-9 col-sm-4 col-md-4 col-lg-4">
                            <div class="form-group">
                                <input type="date" class="form-control" id="dateinput" name="PublishDate" value="@string.Format("{0:yyyy-MM-dd}", @Model.PublishDate)" />
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-xs-3 col-sm-2  col-lg-1">
                            <label class="col-sm-12 control-label">
                                <strong>ISSN</strong>
                            </label>
                        </div>
                        <div class="col-xs-9 col-sm-4 col-md-4 col-lg-4">
                            <div class="form-group">
                                <input class="form-control input-md" placeholder="ISSN" name="Issn" type="text" value="@Model.Issn">
                            </div>
                        </div>
                        <div class="col-xs-3 col-sm-2  col-lg-2">
                            <label class="col-sm-12 control-label">
                                <strong>EISSN</strong>
                            </label>
                        </div>
                        <div class="col-xs-9 col-sm-4 col-md-4 col-lg-4">
                            <div class="form-group">
                                <input class="form-control input-md" placeholder="EISSN" name="Eissn" type="text" value="@Model.Eissn">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-3 col-sm-2  col-lg-1">
                            <label class="col-sm-12 control-label">
                                <strong>Volume</strong>
                            </label>
                        </div>
                        <div class="col-xs-9 col-sm-4 col-md-4 col-lg-4">
                            <input class="form-control input-md" placeholder="Volume" name="Volume" type="text" value="@Model.Volume">
                        </div>
                        <div class="col-xs-3 col-sm-2  col-lg-2">
                            <label class="col-sm-12 control-label">
                                <strong>Image</strong>
                            </label>
                        </div>
                        <div class="col-xs-9 col-sm-4 col-md-4 col-lg-4">
                            <div class="form-group">
                                <input type="file" name="PostedFileImage" id="imgInp" class="custom-file-input" style="width:50%;">
                                <input type="hidden" name="Image" id="BackGroundImage" value="@Model.Image" />
                                <img src="~/Images/NewsletterImages/@Model.Image" alt="img" width="50%" id="blah" accept="image/png,image/gif,image/jpeg">
                                <br />
                                <span>Recommended Size: 195*195</span>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12 col-lg-11">
                        <button type="submit" class="btn btn-sm btn-primary pull-right"> Publish </button>
                    </div>

                }
            </div>
        </div>
    </div>

</body>
</html>

Anz.LMJ/Anz.LMJ.StartUp/Views/Management/Index.cshtml
@using Anz.LMJ.BLO.LogicObjects.User
@using Anz.LMJ.BLO.LogicObjects.Submission

@{
    Layout = "~/Views/Shared/_ManagementLayout.cshtml";
    var User = (UserQueueLO)ViewBag.queue;
    var Submissions = (List<SubmissionLO>)ViewBag.unassigned;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style>
        .jarviswidget-editbox {
            display: block;
            padding: 10px;
        }
    </style>
</head>
<body>
    <div id="main" role="main">


        <div id="ribbon">

            <span class="ribbon-button-alignment">
                <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh" rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
                    <i class="fa fa-refresh"></i>
                </span>
            </span>

            <!-- breadcrumb -->
            <ol class="breadcrumb">
                <li>Home</li>
                <li>Submissions</li>
            </ol>


        </div>


        <div id="main-content">
            <div class="row">
                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h1 class="page-title txt-color-blueDark"><i class="fa-fw fa fa-home"></i> Submissions <span>> My Queue</span></h1>
                </div>
                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">

                </div>
            </div>


            <!-- widget grid -->
            <section id="widget-grid" class="">

                <!-- row -->
                <div class="row" style="margin: 0 !important;">
                    <article class="col-sm-12">
                        <!-- new widget -->
                        <div class="jarviswidget" id="wid-id-0" data-widget-togglebutton="false" data-widget-editbutton="false" data-widget-fullscreenbutton="false" data-widget-colorbutton="false" data-widget-deletebutton="false">

                            <header>


                                <ul class="nav nav-tabs pull-right in" id="myTab">
                                    <li class="active">
                                        <a data-toggle="tab" href="#queue"><i class="fa fa-clock-o"></i> <span class="hidden-mobile hidden-tablet">My Queue</span></a>
                                    </li>
                                    @if (User.isEditor == true || User.isAuthor == true)
                                    {
                                        <li id="unassigned-li">
                                            <a data-toggle="tab" href="#unassigned"> <i class="fa fa-clock-o"></i> <span class="hidden-mobile hidden-tablet">Unassigned</span></a>
                                        </li>
                                    }



                                    <li>
                                        <a data-toggle="tab" href="#active"> <i class="fa fa-clock-o"></i> <span class="hidden-mobile hidden-tablet">All Active</span></a>
                                    </li>

                                    <li>
                                        <a data-toggle="tab" href="#archive"><i class="fa fa-clock-o"></i> <span class="hidden-mobile hidden-tablet">Archives</span></a>
                                    </li>
                                </ul>

                            </header>

                            <!-- widget div-->
                            <div class="no-padding">

                                <!-- end widget edit box -->

                                <div class="widget-body">
                                    <!-- content -->
                                    <div id="myTabContent" class="tab-content">
                                        <div class="tab-pane fade active in padding-10 no-padding-bottom" id="queue">

                                            <!-- MAIN CONTENT -->
                                            <div class="tab-content">
                                                @if (User.isAuthor)
                                                {

                                                    @Html.Partial("_PartialQueueDataTable", User.asAuthor, new ViewDataDictionary { new KeyValuePair<string, object>("Title", "My Author") });

                                                }

                                                @if (User.isEditor)
                                                {
                                                    //<p>author</p>

                                                    @Html.Partial("_PartialQueueDataTable", User.asEditor, new ViewDataDictionary { new KeyValuePair<string, object>("Title", "My Editing") });

                                                }
                                                @if (User.isCopyEditor)
                                                {
                                                    // <p>author</p>
                                                    @Html.Partial("_PartialQueueDataTable", User.asCopyEditor, new ViewDataDictionary { new KeyValuePair<string, object>("Title", "My CopyEditor") });


                                                }
                                                @if (User.isProofReader)
                                                {
                                                    // <p>author</p>
                                                    @Html.Partial("_PartialQueueDataTable", User.asProofReader, new ViewDataDictionary { new KeyValuePair<string, object>("Title", "My Proofreader") });


                                                }
                                                @if (User.isReviewer)
                                                {
                                                    // <p>author</p>
                                                    @Html.Partial("_PartialQueueDataTable", User.asReviewer, new ViewDataDictionary { new KeyValuePair<string, object>("Title", "My Reviewing") });


                                                }
                                            </div>
                                        </div>

                                        <div class="tab-pane fade  in padding-10 no-padding-bottom" id="unassigned">
                                            <div class="tab-content">
                                                @Html.Partial("_PartialUnAssignedDataTable", new ViewDataDictionary { new KeyValuePair<string, object>("Title", "UnAssigned") , new KeyValuePair<string, object>("Submissions", Submissions) });
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>

            </section>

        </div>

</body>
</html>

Anz.LMJ/Anz.LMJ.StartUp/Views/Management/MainMenu.cshtml
@{
    ViewBag.Title = "MainMenu";
    Layout = "~/Views/Shared/_ManagementLayout.cshtml";
}
<div id="main" role="main">
    <div id="content">
        <section id="widget-grid" class="">
            <div class="row">
                <div class="col-xs-0 col-sm-0 col-md-1 col-lg-2">
                </div>
                <div class="col-xs-12 col-sm-12 col-md-10 col-lg-9">

                    <div class="jarviswidget" id="wid-id-1" data-widget-editbutton="false" data-widget-custombutton="false">
                        <header>
                            <span class="widget-icon"><i class="fa fa-edit"></i></span>
                            <h2>New Submission</h2>
                        </header>
                        <div>
                            <div class="jarviswidget-editbox">
                            </div>
                            <div class="widget-body no-padding">
                                <br />
                                <fieldset>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-12 control-label">
                                                    <a id="btn-datatable" href="/Submission/index"><strong>New Manuiscript</strong></a> 
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-12 control-label">
                                                    <strong>Submission send and back to author</strong>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-12 control-label">
                                                    <strong>Incomplete</strong>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-12 control-label">
                                                    <strong>Submission waiting for author approved</strong>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-12 control-label">
                                                    <strong>Submission being in process</strong>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

Anz.LMJ/Anz.LMJ.StartUp/Views/Management/NewsletterForm.cshtml
@using Anz.LMJ.BLO.LogicObjects.Submission
@model List<NewsletterLO>

@{
    ViewBag.Title = "NewsletterForm";
    Layout = "~/Views/Shared/_ManagementLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>

    <style>
        #content {
            text-align: right;
        }
        #newsletter-form {
            width: 80%;
        }
    </style>

    <meta name="viewport" content="width=device-width" />
    <title>Newsletter</title>
</head>
<body>
    <div id="main" role="main">
        <div id="content">
            <div class="row">
                @using (Html.BeginForm("AddNewsletter", "Management", FormMethod.Post, new { @class = "AddNewsletter", enctype = "multipart/form-data" }))
                {<div class="row">
                        <div class="col-xs-3 col-sm-2 col-lg-1">
                            <label class="col-sm-12 control-label">
                                <strong>Name</strong>
                            </label>
                        </div>
                        <div class="col-xs-9 col-sm-4 col-md-4 col-lg-4">
                            <div class="form-group">
                                <input class="form-control input-md" placeholder="Name" name="Name" type="text">
                                <input class="form-control input-md" name="Id" type="hidden">
                            </div>
                        </div>
                        <div class="col-xs-3 col-sm-2  col-lg-2">
                            <label class="col-sm-12 control-label">
                                <strong>Date</strong>
                            </label>
                        </div>
                        <div class="col-xs-9 col-sm-4 col-md-4 col-lg-4">
                            <div class="form-group">
                                <input type="date" class="form-control" name="PublishDate" />
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-xs-3 col-sm-2  col-lg-1">
                            <label class="col-sm-12 control-label">
                                <strong>ISSN</strong>
                            </label>
                        </div>
                        <div class="col-xs-9 col-sm-4 col-md-4 col-lg-4">
                            <div class="form-group">
                                <input class="form-control input-md" placeholder="ISSN" name="Issn" type="text">
                            </div>
                        </div>
                        <div class="col-xs-3 col-sm-2  col-lg-2">
                            <label class="col-sm-12 control-label">
                                <strong>EISSN</strong>
                            </label>
                        </div>
                        <div class="col-xs-9 col-sm-4 col-md-4 col-lg-4">
                            <div class="form-group">
                                <input class="form-control input-md" placeholder="EISSN" name="Eissn" type="text">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-3 col-sm-2  col-lg-1">
                            <label class="col-sm-12 control-label">
                                <strong>Volume</strong>
                            </label>
                        </div>
                        <div class="col-xs-9 col-sm-4 col-md-4 col-lg-4">
                            <input class="form-control input-md" placeholder="Volume" name="Volume" type="text">
                        </div>
                        <div class="col-xs-3 col-sm-2  col-lg-2">
                            <label class="col-sm-12 control-label">
                                <strong>Image</strong>
                            </label>
                        </div>
                        <div class="col-xs-9 col-sm-4 col-md-4 col-lg-4">
                            <div class="form-group">
                                <input type="file" name="PostedFileImage" id="imgInp" class="custom-file-input" style="width:50%;">
                                <input type="hidden" name="Image"  id="BackGroundImage" value="" />
                                <img src="" alt="img" width="50%" id="blah" accept="image/png,image/gif,image/jpeg">
                                <br />
                                <span>Recommended Size: 195*195</span>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12 col-lg-11">
                        <button type="submit" class="btn btn-sm btn-primary pull-right"> Publish </button>
                    </div>

                }
            </div>
        </div>
        </div>
</body>
</html>